class KenyaCounty {
  const KenyaCounty({
    required this.id,
    required this.name,
    required this.subcounties,
    this.governorName,
    this.governorParty,
  });

  final int id;
  final String name;
  final String? governorName;
  final String? governorParty;
  final List<KenyaSubcounty> subcounties;
}

class KenyaSubcounty {
  const KenyaSubcounty({
    required this.id,
    required this.name,
    this.mpName,
    this.mpParty,
  });

  final int id;
  final String name;
  final String? mpName;
  final String? mpParty;
}

const kenyaCounties = [
  KenyaCounty(
    id: 1,
    name: 'Mombasa',
    governorName: 'Abdulswamad Nassir',
    subcounties: [
      KenyaSubcounty(
        id: 101,
        name: 'Changamwe',
        mpName: 'Shimbwa, Omar Mwinyi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 102,
        name: 'Jomvu',
        mpName: 'Bady, Bady Twalib',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 103,
        name: 'Kisauni',
        mpName: 'Bedzumba, Rashid juma',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 104,
        name: 'Nyali',
        mpName: 'Mohamed, Mohamed Ali',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 105,
        name: 'Likoni',
        mpName: 'Mboko, Mishi Juma Khamisi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 106,
        name: 'Mvita',
        mpName: 'Machele, Mohamed Soud',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 2,
    name: 'Kwale',
    governorName: 'Fatuma Achani',
    subcounties: [
      KenyaSubcounty(
        id: 201,
        name: 'Msambweni',
        mpName: 'Bader, Salim Feisal',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 202,
        name: 'Lungalunga',
        mpName: 'Chiforomodo, Mangale Munga',
        mpParty: 'UDM',
      ),
      KenyaSubcounty(
        id: 203,
        name: 'Matuga',
        mpName: 'Tandaza, Kassim Sawa',
        mpParty: 'ANC',
      ),
      KenyaSubcounty(
        id: 204,
        name: 'Kinango',
        mpName: 'Rai, Samuel Gonzi',
        mpParty: 'PAA',
      ),
    ],
  ),
  KenyaCounty(
    id: 3,
    name: 'Kilifi',
    governorName: "Gideon Mung'aro",
    subcounties: [
      KenyaSubcounty(
        id: 301,
        name: 'Kilifi North',
        mpName: 'Baya, Owen Yan',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 302,
        name: 'Kilifi South',
        mpName: 'Kiti, Richard Ken Chonga',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 303,
        name: 'Kaloleni',
        mpName: 'Katana, Paul Kahindi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 304,
        name: 'Rabai',
        mpName: 'Mupe, Anthony Kenga',
        mpParty: 'PAA',
      ),
      KenyaSubcounty(
        id: 305,
        name: 'Ganze',
        mpName: 'Tungule, Charo Kenneth Kazungu',
        mpParty: 'PAA',
      ),
      KenyaSubcounty(
        id: 306,
        name: 'Malindi',
        mpName: 'Mnyazi, Amina Laura',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 307,
        name: 'Magarini',
        mpName: 'Kombe, Harrison Garama',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 4,
    name: 'Tana River',
    governorName: 'Dhadho Godhana',
    subcounties: [
      KenyaSubcounty(
        id: 401,
        name: 'Garsen',
        mpName: 'Guyo, Ali Wario',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 402,
        name: 'Galole',
        mpName: 'Hiribae, Said Buya',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 403,
        name: 'Bura',
        mpName: 'Yakub, Adow Kuno',
        mpParty: 'UPIA',
      ),
    ],
  ),
  KenyaCounty(
    id: 5,
    name: 'Lamu',
    governorName: 'Issa Abdallah Timamy',
    subcounties: [
      KenyaSubcounty(
        id: 501,
        name: 'Lamu East',
        mpName: 'Obo, Ruweida Mohamed',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 502,
        name: 'Lamu West',
        mpName: 'Muiruri, Muthama Stanley',
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 6,
    name: 'Taita Taveta',
    governorName: 'Andrew Mwadime',
    subcounties: [
      KenyaSubcounty(
        id: 601,
        name: 'Taveta',
        mpName: 'Bwire, John Okano',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 602,
        name: 'Wundanyi',
        mpName: 'Mwakuwona, Danson Mwashako',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 603,
        name: 'Mwatate',
        mpName: 'Shake, Peter Mbogho',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 604,
        name: 'Voi',
        mpName: 'Abdi, Khamis Chome',
        mpParty: 'WDM',
      ),
    ],
  ),
  KenyaCounty(
    id: 7,
    name: 'Garissa',
    governorName: 'Nathif Jama',
    subcounties: [
      KenyaSubcounty(
        id: 701,
        name: 'Garissa Township',
        mpName: 'Barrow, Dekow Mohamed',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 702,
        name: 'Balambala',
        mpName: 'Shurie, Abdi Omar',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 703,
        name: 'Lagdera',
        mpName: 'Mohamed, Abdikadir Hussein',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 704,
        name: 'Dadaab',
        mpName: 'Maalim, Farah',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 705,
        name: 'Fafi',
        mpName: 'Yakub, Farah Salah',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 706,
        name: 'Ijara',
        mpName: 'Abdi, Abdi Ali',
        mpParty: 'NAP-K',
      ),
    ],
  ),
  KenyaCounty(
    id: 8,
    name: 'Wajir',
    governorName: 'Ahmed Abdullahi',
    subcounties: [
      KenyaSubcounty(
        id: 801,
        name: 'Wajir North',
        mpName: 'Saney, Ibrahim Abdi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 802,
        name: 'Wajir East',
        mpName: 'Mohamed, Aden Daudi',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 803,
        name: 'Tarbaj',
        mpName: 'Barre, Hussein Abdi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 804,
        name: 'Wajir West',
        mpName: 'Farah, Yussuf Mohamed',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 805,
        name: 'Eldas',
        mpName: 'Wehliye, Adan Keynan',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 806,
        name: 'Wajir South',
        mpName: 'Adow, Mohamed Aden',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 9,
    name: 'Mandera',
    governorName: 'Mohamed Adan Khalif',
    subcounties: [
      KenyaSubcounty(
        id: 901,
        name: 'Mandera West',
        mpName: 'Yussuf, Adan Haji',
        mpParty: 'UDM',
      ),
      KenyaSubcounty(
        id: 902,
        name: 'Banissa',
        mpName: 'Vacant',
        mpParty: 'UDM',
      ),
      KenyaSubcounty(
        id: 903,
        name: 'Mandera North',
        mpName: 'Abdullahi, Bashir Sheikh',
        mpParty: 'UDM',
      ),
      KenyaSubcounty(
        id: 904,
        name: 'Mandera South',
        mpName: 'Haro, Abdul Ebrahim',
        mpParty: 'UDM',
      ),
      KenyaSubcounty(
        id: 905,
        name: 'Mandera East',
        mpName: 'Abdirahman, Husseinweytan Mohamed',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 906,
        name: 'Lafey',
        mpName: 'Abdirahman, Mohamed Abdi',
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 10,
    name: 'Marsabit',
    governorName: 'Mohamud Ali',
    subcounties: [
      KenyaSubcounty(
        id: 1001,
        name: 'Moyale',
        mpName: 'Jaldesa, Guyo Waqo',
        mpParty: 'UPIA',
      ),
      KenyaSubcounty(
        id: 1002,
        name: 'North Horr',
        mpName: 'Guyo, Adhe Wario',
        mpParty: 'KANU',
      ),
      KenyaSubcounty(
        id: 1003,
        name: 'Saku',
        mpName: 'Raso, Dido Ali',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1004,
        name: 'Laisamis',
        mpName: 'Lekuton, Joseph',
        mpParty: 'UDM',
      ),
    ],
  ),
  KenyaCounty(
    id: 11,
    name: 'Isiolo',
    governorName: 'Abdi Hassan Guyo',
    subcounties: [
      KenyaSubcounty(
        id: 1101,
        name: 'Isiolo North',
        mpName: 'Lomwa, Joseph Samal',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 1102,
        name: 'Isiolo South',
        mpName: 'Tubi, Bidu Mohamed',
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 12,
    name: 'Meru',
    governorName: 'Kawira Mwangaza',
    subcounties: [
      KenyaSubcounty(
        id: 1201,
        name: 'Igembe South',
        mpName: 'Mwiringi, John Paul',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1202,
        name: 'Igembe Central',
        mpName: 'Karitho, Kiili Daniel',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 1203,
        name: 'Igembe North',
        mpName: "M'Anaiba, Julius Taitumu",
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1204,
        name: 'Tigania West',
        mpName: 'Mutunga, John Kanyuithia',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1205,
        name: 'Tigania East',
        mpName: 'Aburi, Lawrence Mpuru',
        mpParty: 'NOPEU',
      ),
      KenyaSubcounty(
        id: 1206,
        name: 'North Imenti',
        mpName: 'Abdul, Rahim Dawood',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 1207,
        name: 'Buuri',
        mpName: 'Murwithania, Rindikiri Mugambi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1208,
        name: 'Central Imenti',
        mpName: 'Kirima, Moses Nguchine',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1209,
        name: 'South Imenti',
        mpName: 'Ithinji, Dr. Shadrack Mwiti',
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 13,
    name: 'Tharaka-Nithi',
    governorName: 'Muthomi Njuki',
    subcounties: [
      KenyaSubcounty(
        id: 1301,
        name: 'Maara',
        mpName: 'Mbiuki, Japhet Miriti Kareke',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1302,
        name: 'Chuka/Igambangombe',
        mpName: 'Ntwiga, Patrick Munene',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1303,
        name: 'Tharaka',
        mpName: 'Murugara, George Gitonga',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 14,
    name: 'Embu',
    governorName: 'Cecily Mbarire',
    subcounties: [
      KenyaSubcounty(
        id: 1401,
        name: 'Manyatta',
        mpName: 'Mukunji, John Gitonga Mwaniki',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1402,
        name: 'Runyenjes',
        mpName: 'Karemba, Eric Muchangi Njiru',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1403,
        name: 'Mbeere South',
        mpName: 'Nebart, Bernard Muriuki',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 1404,
        name: 'Mbeere North',
        mpName: 'Ruku, Geoffrey Kariuki Kiringa',
        mpParty: 'DP',
      ),
    ],
  ),
  KenyaCounty(
    id: 15,
    name: 'Kitui',
    governorName: 'Julius Malombe',
    subcounties: [
      KenyaSubcounty(
        id: 1501,
        name: 'Mwingi North',
        mpName: 'Nzengu, Paul Musyimi',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1502,
        name: 'Mwingi West',
        mpName: 'Nguna, Charles Ngusya',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1503,
        name: 'Mwingi Central',
        mpName: 'Mulyungi, Gideon Mutemi',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1504,
        name: 'Kitui West',
        mpName: 'Nyenze, Edith Vethi',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1505,
        name: 'Kitui Rural',
        mpName: 'Mboni, David Mwalika',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1506,
        name: 'Kitui Central',
        mpName: 'Mulu, Makali Benson',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1507,
        name: 'Kitui East',
        mpName: 'Mbai, Nimrod Mbithuka',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1508,
        name: 'Kitui South',
        mpName: 'Nyamai, Rachael Kaki',
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 16,
    name: 'Machakos',
    governorName: 'Wavinya Ndeti',
    subcounties: [
      KenyaSubcounty(
        id: 1601,
        name: 'Masinga',
        mpName: 'Mwalyo, Joshua Mbithi Mutua',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 1602,
        name: 'Yatta',
        mpName: 'Basil, Robert Ngui',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1603,
        name: 'Kangundo',
        mpName: 'Muli, Fabian Kyule',
        mpParty: 'GDDP',
      ),
      KenyaSubcounty(
        id: 1604,
        name: 'Matungulu',
        mpName: 'Mule, Stephen Mutinda',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1605,
        name: 'Kathiani',
        mpName: 'Mbui, Robert',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1606,
        name: 'Mavoko',
        mpName: 'Kingola, Patrick Makau',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1607,
        name: 'Machakos Town',
        mpName: 'Mule, Caleb Mutiso',
        mpParty: 'MCCP',
      ),
      KenyaSubcounty(
        id: 1608,
        name: 'Mwala',
        mpName: 'Musau, Vincent Musyoka',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 17,
    name: 'Makueni',
    governorName: 'Mutula Kilonzo',
    subcounties: [
      KenyaSubcounty(
        id: 1701,
        name: 'Mbooni',
        mpName: 'Nzioka, Erastus Kivasu',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1702,
        name: 'Kilome',
        mpName: 'Nzambia, Thudeeus Kithua',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1703,
        name: 'Kaiti',
        mpName: 'Kimilu, Joshua Kivinda',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1704,
        name: 'Makueni',
        mpName: 'Kiamba, Suzanne Ndunge',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 1705,
        name: 'Kibwezi West',
        mpName: 'Mutuse, Eckomas Mwengi',
        mpParty: 'MCCP',
      ),
      KenyaSubcounty(
        id: 1706,
        name: 'Kibwezi East',
        mpName: 'Mbalu, Jessica Nduku Kiko',
        mpParty: 'WDM',
      ),
    ],
  ),
  KenyaCounty(
    id: 18,
    name: 'Nyandarua',
    governorName: 'Moses Kiarie Badilisha',
    subcounties: [
      KenyaSubcounty(
        id: 1801,
        name: 'Kinangop',
        mpName: 'Kwenya, Thuku Zachary',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 1802,
        name: 'Kipipiri',
        mpName: 'Muhia, Wanjiku',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1803,
        name: 'Ol Kalou',
        mpName: 'Kiaraho, David Njuguna',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 1804,
        name: 'Ol Jorok',
        mpName: 'Muchira, Michael Mwangi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1805,
        name: 'Ndaragwa',
        mpName: 'Gachagua, George N.',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 19,
    name: 'Nyeri',
    governorName: 'Mutahi Kahiga',
    subcounties: [
      KenyaSubcounty(
        id: 1901,
        name: 'Tetu',
        mpName: 'Mwangi, Geoffrey Wandeto',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1902,
        name: 'Kieni',
        mpName: 'Wainaina, Antony Njoroge',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1903,
        name: 'Mathira',
        mpName: 'Kahugu, Eric Meangi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1904,
        name: 'Othaya',
        mpName: 'Wainaina, Michael Wambugu',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1905,
        name: 'Mukurweini',
        mpName: 'Gichohi, Kaguchia John Philip',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 1906,
        name: 'Nyeri Town',
        mpName: 'Mathenge, Duncan Maina',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 20,
    name: 'Kirinyaga',
    governorName: 'Anne Waiguru',
    subcounties: [
      KenyaSubcounty(
        id: 2001,
        name: 'Mwea',
        mpName: 'Maingi, Mary',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2002,
        name: 'Gichugu',
        mpName: 'Githinji, Robert Gichimu',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2003,
        name: 'Ndia',
        mpName: 'GK, George Macharia Kariuki',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2004,
        name: 'Kirinyaga Central',
        mpName: 'Gitari, Joseph Gachoki',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 21,
    name: "Murang'a",
    governorName: "Irungu Kang'ata",
    subcounties: [
      KenyaSubcounty(
        id: 2101,
        name: 'Kangema',
        mpName: 'Kihungi, Peter Irungu',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2102,
        name: 'Mathioya',
        mpName: 'Gichuki, Edwin Mugo',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2103,
        name: 'Kiharu',
        mpName: 'Nyoro, Samson Ndindi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2104,
        name: 'Kigumo',
        mpName: 'Munyoro, Joseph Kamau',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2105,
        name: 'Maragwa',
        mpName: 'Njoroge, Mary Wamaua Waithira',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2106,
        name: 'Kandara',
        mpName: 'Njuguna, Chege',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2107,
        name: 'Gatanga',
        mpName: 'Muriu, Wakili Edward',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 22,
    name: 'Kiambu',
    governorName: 'Kimani Wamatangi',
    subcounties: [
      KenyaSubcounty(
        id: 2201,
        name: 'Gatundu South',
        mpName: 'Kagombe, Gabriel Gathuka',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2202,
        name: 'Gatundu North',
        mpName: 'Kururia, Elijah Njore Njoroge',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 2203,
        name: 'Juja',
        mpName: 'Ndungu, George Koimburi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2204,
        name: 'Thika Town',
        mpName: 'Nganga, Alice Wambui',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2205,
        name: 'Ruiru',
        mpName: 'Kingara, Simon Nganga',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2206,
        name: 'Githunguri',
        mpName: 'Wamuchomba, Gathoni',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2207,
        name: 'Kiambu',
        mpName: 'Waithaka, John Machua',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2208,
        name: 'Kiambaa',
        mpName: 'John Njuguna',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2209,
        name: 'Kabete',
        mpName: 'Wamacukuru, James Githua Kamau',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2210,
        name: 'Kikuyu',
        mpName: "Ichung'wah, Anthony Kimani",
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2211,
        name: 'Limuru',
        mpName: 'Chege, John Kiragu',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2212,
        name: 'Lari',
        mpName: 'Kahangara, Joseph Mburu',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 23,
    name: 'Turkana',
    governorName: 'Jeremiah Lomurkai',
    subcounties: [
      KenyaSubcounty(
        id: 2301,
        name: 'Turkana North',
        mpName: 'Naibun, Paul Ekwom',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 2302,
        name: 'Turkana West',
        mpName: 'Nanok, Daniel Epuyo',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2303,
        name: 'Turkana Central',
        mpName: 'Emathe, Joseph Namuar',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2304,
        name: 'Loima',
        mpName: 'Akuja, Protus Ewesit',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2305,
        name: 'Turkana South',
        mpName: 'Namoit, John Ariko',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 2306,
        name: 'Turkana East',
        mpName: "Ngikolong, Nicholas Ng'ikor Nixon",
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 24,
    name: 'West Pokot',
    governorName: 'Simon Kachapin',
    subcounties: [
      KenyaSubcounty(
        id: 2401,
        name: 'Kapenguria',
        mpName: 'Chumel, Samwel Moroto',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2402,
        name: 'Sigor',
        mpName: 'Lochakapong, Peter',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2403,
        name: 'Kacheliba',
        mpName: 'Titus, Lotee',
        mpParty: 'KUP',
      ),
      KenyaSubcounty(
        id: 2404,
        name: 'Pokot South',
        mpName: 'Pkosing, David Losiakou',
        mpParty: 'KUP',
      ),
    ],
  ),
  KenyaCounty(
    id: 25,
    name: 'Samburu',
    governorName: 'Jonathan Lati Lelelit',
    subcounties: [
      KenyaSubcounty(
        id: 2501,
        name: 'Samburu West',
        mpName: 'Lesuuda, Josephine Naisula',
        mpParty: 'KANU',
      ),
      KenyaSubcounty(
        id: 2502,
        name: 'Samburu North',
        mpName: 'Letipila, Dominic Eli',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2503,
        name: 'Samburu East',
        mpName: 'Lentoijoni, Jackson Lekumontare',
        mpParty: 'KANU',
      ),
    ],
  ),
  KenyaCounty(
    id: 26,
    name: 'Trans Nzoia',
    governorName: 'George Natembeya',
    subcounties: [
      KenyaSubcounty(
        id: 2601,
        name: 'Kwanza',
        mpName: 'Wanyonyi, Ferdinand Kevin',
        mpParty: 'FORD-K',
      ),
      KenyaSubcounty(
        id: 2602,
        name: 'Endebess',
        mpName: 'Pukose, Robert (Dr.)',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2603,
        name: 'Saboti',
        mpName: 'Luyai, Caleb Amisi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 2604,
        name: 'Kiminini',
        mpName: 'Bisau, Maurice Kakai',
        mpParty: 'DAP-K',
      ),
      KenyaSubcounty(
        id: 2605,
        name: 'Cherangany',
        mpName: 'Barasa, Patrick Simiyu',
        mpParty: 'DAP-K',
      ),
    ],
  ),
  KenyaCounty(
    id: 27,
    name: 'Uasin Gishu',
    governorName: 'Jonathan Bii',
    subcounties: [
      KenyaSubcounty(
        id: 2701,
        name: 'Soy',
        mpName: 'Kiplagat, David',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2702,
        name: 'Turbo',
        mpName: 'Sitienei, Janet Jepkemboi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2703,
        name: 'Moiben',
        mpName: 'Bartoo, Phylis Jepkemoi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2704,
        name: 'Ainabkoi',
        mpName: 'Chepkonga, Kiprono Samwel',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2705,
        name: 'Kapseret',
        mpName: 'Sudi, Oscar Kipchumba',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2706,
        name: 'Kesses',
        mpName: 'Rutto, Julius Kipletting',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 28,
    name: 'Elgeyo-Marakwet',
    governorName: 'Wisley Rotich',
    subcounties: [
      KenyaSubcounty(
        id: 2801,
        name: 'Marakwet East',
        mpName: 'Bowen, David Kangogo',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2802,
        name: 'Marakwet West',
        mpName: 'Toroitich, Timothy Kipchumba',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 2803,
        name: 'Keiyo North',
        mpName: 'Korir, Adams Kipsanai',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2804,
        name: 'Keiyo South',
        mpName: 'Kipkoech, Gideon Kimaiyo',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 29,
    name: 'Nandi',
    governorName: 'Stephen Sang',
    subcounties: [
      KenyaSubcounty(
        id: 2901,
        name: 'Tinderet',
        mpName: 'Kipbiwot, Julius Melly',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2902,
        name: 'Aldai',
        mpName: 'Kitany, Marianne Jebet',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2903,
        name: 'Nandi Hills',
        mpName: 'Kitur, Bernard Kibor',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2904,
        name: 'Chesumei',
        mpName: 'Biego, Paul Kibichy',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2905,
        name: 'Emgwen',
        mpName: 'Lelmengit, Josses Kiptoo Kosgey',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 2906,
        name: 'Mosop',
        mpName: 'Kirwa, Abraham Kipsang',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 30,
    name: 'Baringo',
    governorName: 'Benjamin Cheboi',
    subcounties: [
      KenyaSubcounty(
        id: 3001,
        name: 'Tiaty',
        mpName: 'Kassait, William Kamket',
        mpParty: 'KANU',
      ),
      KenyaSubcounty(
        id: 3002,
        name: 'Baringo North',
        mpName: 'Kipkoros, Joseph Makilap',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3003,
        name: 'Baringo Central',
        mpName: 'Kandie, Joshua Chepyegon',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3004,
        name: 'Baringo South',
        mpName: 'Kamuren, Charles',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3005,
        name: 'Mogotio',
        mpName: 'Kipgnor, Reuben Kiborek',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3006,
        name: 'Eldama Ravine',
        mpName: 'Sirma, Musa Cherutich',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 31,
    name: 'Laikipia',
    governorName: 'Joshua Irungu',
    subcounties: [
      KenyaSubcounty(
        id: 3101,
        name: 'Laikipia West',
        mpName: 'Karani, Stephen Wachira',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3102,
        name: 'Laikipia East',
        mpName: 'Kiunjuri, Festus Mwangi',
        mpParty: 'TSP',
      ),
      KenyaSubcounty(
        id: 3103,
        name: 'Laikipia North',
        mpName: 'Korere, Sarah Paulata',
        mpParty: 'JP',
      ),
    ],
  ),
  KenyaCounty(
    id: 32,
    name: 'Nakuru',
    governorName: 'Susan Kihika',
    subcounties: [
      KenyaSubcounty(
        id: 3201,
        name: 'Molo',
        mpName: 'Kimani, Francis Kuria',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3202,
        name: 'Njoro',
        mpName: 'Chepkwony, Charity Kathambi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3203,
        name: 'Naivasha',
        mpName: 'Kihara, Jayne Wanjiru Njeru',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3204,
        name: 'Gilgil',
        mpName: 'Wanjira, Martha Wangari',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3205,
        name: 'Kuresoi South',
        mpName: 'Tonui, Joseph Kipkosgei',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3206,
        name: 'Kuresoi North',
        mpName: 'Kiprono, Mutai Alfred',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3207,
        name: 'Subukia',
        mpName: 'Gachobe, Samuel Kinuthia',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3208,
        name: 'Rongai',
        mpName: 'Chebor, Paul Kibet',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3209,
        name: 'Bahati',
        mpName: 'Mrembo, Irene Njoki',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 3210,
        name: 'Nakuru Town West',
        mpName: 'Arama, Samuel',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 3211,
        name: 'Nakuru Town East',
        mpName: 'Gikaria, David',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 33,
    name: 'Narok',
    governorName: 'Patrick Ole Ntutu',
    subcounties: [
      KenyaSubcounty(
        id: 3301,
        name: 'Kilgoris',
        mpName: 'Sunkuli, Julius Lekakeny Ole',
        mpParty: 'KANU',
      ),
      KenyaSubcounty(
        id: 3302,
        name: 'Emurua Dikirr',
        mpName: "Kipyegon, Johana Ng'eno",
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3303,
        name: 'Narok North',
        mpName: 'Pareiyo, Agnes Mantaine',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 3304,
        name: 'Narok East',
        mpName: 'Lemanken, Aramat',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3305,
        name: 'Narok South',
        mpName: 'Kitilai, Ole Ntutu',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 3306,
        name: 'Narok West',
        mpName: 'Tongoyo, Gabriel Koshal',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 34,
    name: 'Kajiado',
    governorName: 'Joseph Ole Lenku',
    subcounties: [
      KenyaSubcounty(
        id: 3401,
        name: 'Kajiado North',
        mpName: 'Nguro, Onesmus Ngogoyo',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3402,
        name: 'Kajiado Central',
        mpName: 'Kanchory, Elijah Memusi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3403,
        name: 'Kajiado East',
        mpName: 'Hamisi, Kakuta Maimai',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3404,
        name: 'Kajiado West',
        mpName: 'Risa, Sunkuiya George',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3405,
        name: 'Kajiado South',
        mpName: 'Sakimba, Parashina Samuel',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 35,
    name: 'Kericho',
    governorName: 'Erick Mutai',
    subcounties: [
      KenyaSubcounty(
        id: 3501,
        name: 'Kipkelion East',
        mpName: 'Cherorot, Joseph Kimutai',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3502,
        name: 'Kipkelion West',
        mpName: 'Kosgei, Hilary Kiplangat',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3503,
        name: 'Ainamoi',
        mpName: 'Langat, Benjamin Kipkirui',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3504,
        name: 'Bureti',
        mpName: 'Komingoi, Kibet Kirui',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3505,
        name: 'Belgut',
        mpName: 'Koech, Nelson',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3506,
        name: 'Sigowet/Soin',
        mpName: 'Kemei, Justice Kipsang',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 36,
    name: 'Bomet',
    governorName: 'Hillary Barchok',
    subcounties: [
      KenyaSubcounty(
        id: 3601,
        name: 'Sotik',
        mpName: 'Sigei, Francis Kipyegon arap',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3602,
        name: 'Chepalungu',
        mpName: 'Koech, Victor Kipngetich',
        mpParty: 'CCM',
      ),
      KenyaSubcounty(
        id: 3603,
        name: 'Bomet East',
        mpName: 'Yegon, Richard Kipkemoi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3604,
        name: 'Bomet Central',
        mpName: 'Kilel, Richard Cheruiyot',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3605,
        name: 'Konoin',
        mpName: 'Yegon, Brighton Leonard',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 37,
    name: 'Kakamega',
    governorName: 'Fernandes Barasa',
    subcounties: [
      KenyaSubcounty(
        id: 3701,
        name: 'Lugari',
        mpName: 'Nabii, Nabwera Daraja',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3702,
        name: 'Likuyani',
        mpName: 'Mugabe, Innocent Maino',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3703,
        name: 'Malava',
        mpName: 'Injendi, Moses Malulu',
        mpParty: 'ANC',
      ),
      KenyaSubcounty(
        id: 3704,
        name: 'Lurambi',
        mpName: 'Mukhwana, Titus Khamala',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3705,
        name: 'Navakholo',
        mpName: 'Wangwe, Emmanuel',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3706,
        name: 'Mumias West',
        mpName: 'Naicca, Johnson Manya',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3707,
        name: 'Mumias East',
        mpName: 'Salasya, Peter Kalerwa',
        mpParty: 'DAP-K',
      ),
      KenyaSubcounty(
        id: 3708,
        name: 'Matungu',
        mpName: 'Nabulindo, Peter Oscar',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3709,
        name: 'Butere',
        mpName: 'Mwale, Nicholas S. Tindi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3710,
        name: 'Khwisero',
        mpName: 'Wangaya, Christopher Aseka',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 3711,
        name: 'Shinyalu',
        mpName: 'IkanaM, Frederick Lusuli',
        mpParty: 'ANC',
      ),
      KenyaSubcounty(
        id: 3712,
        name: 'Ikolomani',
        mpName: 'Shinali, Bernard Masaka',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 38,
    name: 'Vihiga',
    governorName: 'Wilberforce Ottichilo',
    subcounties: [
      KenyaSubcounty(
        id: 3801,
        name: 'Vihiga',
        mpName: 'Kagesi, Kivai Ernest Ogesi',
        mpParty: 'ANC',
      ),
      KenyaSubcounty(
        id: 3802,
        name: 'Sabatia',
        mpName: 'Logova, Sloya Clement',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3803,
        name: 'Hamisi',
        mpName: 'Gimose, Charles Gumini',
        mpParty: 'ANC',
      ),
      KenyaSubcounty(
        id: 3804,
        name: 'Luanda',
        mpName: 'Oyugi, Dick Maungu',
        mpParty: 'DAP-K',
      ),
      KenyaSubcounty(
        id: 3805,
        name: 'Emuhaya',
        mpName: 'Omboko, Milemba Jeremiah',
        mpParty: 'ANC',
      ),
    ],
  ),
  KenyaCounty(
    id: 39,
    name: 'Bungoma',
    governorName: 'Kenneth Lusaka',
    subcounties: [
      KenyaSubcounty(
        id: 3901,
        name: 'Mt. Elgon',
        mpName: 'Chesebe, Fred Kapondi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3902,
        name: 'Sirisia',
        mpName: 'Koyi, John Waluke',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 3903,
        name: 'Kabuchai',
        mpName: 'Kalasinga, Joseph Simiyu Wekesa Majimbo',
        mpParty: 'FORD-K',
      ),
      KenyaSubcounty(
        id: 3904,
        name: 'Bumula',
        mpName: 'Wamboka, Nelson Jack Wamboka',
        mpParty: 'DAP-K',
      ),
      KenyaSubcounty(
        id: 3905,
        name: 'Kanduyi',
        mpName: 'Makali, John Okwisia',
        mpParty: 'FORD-K',
      ),
      KenyaSubcounty(
        id: 3906,
        name: 'Webuye East',
        mpName: 'Wanyonyi, Martin Pepela',
        mpParty: 'FORD-K',
      ),
      KenyaSubcounty(
        id: 3907,
        name: 'Webuye West',
        mpName: 'Sitati, Daniel Wanyama',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3908,
        name: 'Kimilili',
        mpName: 'Mutua, Didmus Wekesa Barasa',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 3909,
        name: 'Tongaren',
        mpName: 'Murumba, John Chikati',
        mpParty: 'FORD-K',
      ),
    ],
  ),
  KenyaCounty(
    id: 40,
    name: 'Busia',
    governorName: 'Paul Otuoma',
    subcounties: [
      KenyaSubcounty(
        id: 4001,
        name: 'Teso North',
        mpName: 'Oku, Edward Kaunya',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4002,
        name: 'Teso South',
        mpName: 'Otucho, Mary Emaase',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4003,
        name: 'Nambale',
        mpName: 'Mulanya, Geoffrey Ekesa',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 4004,
        name: 'Matayos',
        mpName: 'Odanga, Geoffrey Makokha',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4005,
        name: 'Butula',
        mpName: 'Oyula, Joseph H. Maero',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4006,
        name: 'Funyula',
        mpName: 'Oundo, Wilberforce Ojiambo',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4007,
        name: 'Budalangi',
        mpName: 'Wanjala, Raphael Sauti Bitta',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 41,
    name: 'Siaya',
    governorName: 'James Orengo',
    subcounties: [
      KenyaSubcounty(
        id: 4101,
        name: 'Ugenya',
        mpName: 'Ochieng, David Ouma',
        mpParty: 'MDG',
      ),
      KenyaSubcounty(
        id: 4102,
        name: 'Ugunja',
        mpName: 'Wandayi, James Opiyo',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4103,
        name: 'Alego Usonga',
        mpName: 'Samuel Onunga',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4104,
        name: 'Gem',
        mpName: 'Odhiambo, Elisha Ochieng',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4105,
        name: 'Bondo',
        mpName: 'Ogolla, Gideon Ochanda',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4106,
        name: 'Rarieda',
        mpName: 'Amollo, Paul Otiende',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 42,
    name: 'Kisumu',
    governorName: "Anyang' Nyong'o",
    subcounties: [
      KenyaSubcounty(
        id: 4201,
        name: 'Kisumu East',
        mpName: 'Ahmed, Shakeel Ahmed Shabbir',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 4202,
        name: 'Kisumu West',
        mpName: 'Buyu, Rozaah Akiny',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4203,
        name: 'Kisumu Central',
        mpName: 'Oron, Joshua Odongo',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4204,
        name: 'Seme',
        mpName: 'Nyikal, James Wambura',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4205,
        name: 'Nyando',
        mpName: 'Odoyo, Okello Jared',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4206,
        name: 'Muhoroni',
        mpName: 'Oyoo, James Onyango',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4207,
        name: 'Nyakach',
        mpName: 'Owuor, Joshua Aduma',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 43,
    name: 'Homa Bay',
    governorName: 'Gladys Wanga',
    subcounties: [
      KenyaSubcounty(
        id: 4301,
        name: 'Kasipul',
        mpName: "Were, Charles Ong'ondo",
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4302,
        name: 'Kabondo Kasipul',
        mpName: 'Obara, Eve Akinyi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4303,
        name: 'Karachuonyo',
        mpName: 'Okuome, Andrew Adipo',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4304,
        name: 'Rangwe',
        mpName: 'Gogo, Lilian Achieng',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4305,
        name: 'Homa Bay Town',
        mpName: 'Kaluma, George Peter Opondo',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4306,
        name: 'Ndhiwa',
        mpName: 'Owino, Martin Peters',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4307,
        name: 'Suba North',
        mpName: 'Odhiambo, Millie Grace Akoth',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4308,
        name: 'Suba South',
        mpName: 'Omondi, Caroli',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 44,
    name: 'Migori',
    governorName: 'Ochilo Ayacko',
    subcounties: [
      KenyaSubcounty(
        id: 4401,
        name: 'Rongo',
        mpName: 'Abuor, Paul',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4402,
        name: 'Awendo',
        mpName: 'Owino, John Walter',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4403,
        name: 'Suna East',
        mpName: 'Mohamed, Junet Sheikh Nuh',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4404,
        name: 'Suna West',
        mpName: 'Masara, Peter Francis',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4405,
        name: 'Uriri',
        mpName: 'Nyamita, Mark Ogolla',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4406,
        name: 'Nyatike',
        mpName: 'Odege, Tom Mboya',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4407,
        name: 'Kuria West',
        mpName: 'Robi, Mathias Nyamabe',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4408,
        name: 'Kuria East',
        mpName: 'Kemero, Maisori Marwa Kitayama',
        mpParty: 'UDA',
      ),
    ],
  ),
  KenyaCounty(
    id: 45,
    name: 'Kisii',
    governorName: 'Simba Arati',
    subcounties: [
      KenyaSubcounty(
        id: 4501,
        name: 'Bonchari',
        mpName: 'Onchoke, Charles',
        mpParty: 'UPA',
      ),
      KenyaSubcounty(
        id: 4502,
        name: 'South Mugirango',
        mpName: 'Onyiego, Silvanus Osoro',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4503,
        name: 'Bomachoge Borabu',
        mpName: 'Barongo, Nolfason Obadiah',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4504,
        name: 'Bobasi',
        mpName: 'Momanyi, Innocent Obiri',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 4505,
        name: 'Bomachoge Chache',
        mpName: 'Alfah, Miruka Ondieki',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4506,
        name: 'Nyaribari Masaba',
        mpName: 'Manduku, Daniel Ogwoka',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4507,
        name: 'Nyaribari Chache',
        mpName: 'Jhanda Zaheer',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4508,
        name: 'Kitutu Chache North',
        mpName: 'Mokaya, Nyakundi Japheth',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4509,
        name: 'Kitutu Chache South',
        mpName: 'Kibagendi, Antoney',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 46,
    name: 'Nyamira',
    governorName: 'Amos Nyaribo',
    subcounties: [
      KenyaSubcounty(
        id: 4601,
        name: 'Kitutu Masaba',
        mpName: 'Gisairo, Clive Ombane',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4602,
        name: 'West Mugirango',
        mpName: 'Mogaka, Stephen M.',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 4603,
        name: 'North Mugirango',
        mpName: 'Nyamoko, Joash Nyamache',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4604,
        name: 'Borabu',
        mpName: 'Osero, Patrick Kibagendi',
        mpParty: 'ODM',
      ),
    ],
  ),
  KenyaCounty(
    id: 47,
    name: 'Nairobi',
    governorName: 'Johnson Sakaja',
    subcounties: [
      KenyaSubcounty(
        id: 4701,
        name: 'Westlands',
        mpName: 'Wetangula, Timothy Wanyonyi',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4702,
        name: 'Dagoretti North',
        mpName: 'Elachi, Beatrice Kadeveresia',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4703,
        name: 'Dagoretti South',
        mpName: 'Waweru, John Kiarie',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4704,
        name: 'Langata',
        mpName: 'Khodhe, Phelix Odiwuor',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4705,
        name: 'Kibra',
        mpName: 'Orero, Peter Ochieng',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4706,
        name: 'Roysambu',
        mpName: 'Mwafrika, Augustine Kamande',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4707,
        name: 'Kasarani',
        mpName: 'Karauri, Ronald Kamwiko',
        mpParty: 'Independent',
      ),
      KenyaSubcounty(
        id: 4708,
        name: 'Ruaraka',
        mpName: 'Francis, Kajwang Tom Joseph',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4709,
        name: 'Embakasi South',
        mpName: 'Mawathe, Julius Musili',
        mpParty: 'WDM',
      ),
      KenyaSubcounty(
        id: 4710,
        name: 'Embakasi North',
        mpName: 'Gakuya, James Mwangi',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4711,
        name: 'Embakasi Central',
        mpName: 'Gathiru, Mejjadonk Benjamin',
        mpParty: 'UDA',
      ),
      KenyaSubcounty(
        id: 4712,
        name: 'Embakasi East',
        mpName: 'Ongili, Babu Owino Paul',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4713,
        name: 'Embakasi West',
        mpName: 'Mwenje, Mark Samuel Muriithi',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 4714,
        name: 'Makadara',
        mpName: 'Omwera, George Aladwa',
        mpParty: 'ODM',
      ),
      KenyaSubcounty(
        id: 4715,
        name: 'Kamkunji',
        mpName: 'Hassan, Abdi Yusuf',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 4716,
        name: 'Starehe',
        mpName: 'Maina, Mwago Amos',
        mpParty: 'JP',
      ),
      KenyaSubcounty(
        id: 4717,
        name: 'Mathare',
        mpName: 'Oluoch, Anthony Tom',
        mpParty: 'ODM',
      ),
    ],
  ),
];
